apiVersion: v2
name: frontend
description: A Helm chart for frontend Kubernetes

type: application

version: 2.0.0

# dependencies:
#   - name: ingress-nginx
#     version: 4.6.1
#     repository: https://kubernetes.github.io/ingress-nginx