apiVersion: v2
name: frontend
description: A Helm chart for frontend Kubernetes

type: application

version: 0.2.2

dependencies:
  - name: ingress-nginx
    version: 4.6.1
    repository: https://kubernetes.github.io/ingress-nginx